name: npm-publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true
      - name: run tsc
        run: pnpm build
      - name: Publish to npm
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          commit_pattern: "release: v?(\\S+)$"
          publish_args: --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

